#!/usr/bin/bash

echo "Downloading $1 as $2"

if [[ -z "$5" ]]
then
  SAMPLES_PATH="/home/begin/stream/Stream/Samples"
else
  echo "ITS A THEME!"
  SAMPLES_PATH="/home/begin/stream/Stream/Samples/theme_songs"
fi

# mrsommerfeld: @beginbot youtube-dl --prefer-free-formats

youtube-dl -v --no-cache-dir -x $1 --audio-format="opus" -o "$SAMPLES_PATH/$2.opus"

if [[ -z "$3" && -z "$4" ]]
then
  echo "No Timestamps"
  ffmpeg -i "$SAMPLES_PATH/$2.opus" -y -c:a libvorbis "$SAMPLES_PATH/$2.ogg"
  ffmpeg -i "$SAMPLES_PATH/$2.opus" -y -c:a libvorbis "$SAMPLES_PATH/$2.ogg"
else
  echo "Cutting from $3 to $4"
  ffmpeg -ss $3 -to $4 -i "$SAMPLES_PATH/$2.opus" -y -c:a libvorbis "$SAMPLES_PATH/$2.ogg"
fi

rm "$SAMPLES_PATH/$2.opus"
