#!/usr/bin/bash

echo "Downloading $1 as $2"

# dougthecoder: (?:youtube(?:-nocookie)?\.com/(?:[^/]+/.+/|(?:v|e(?:mbed)?)/|.*[?&]v=)|youtu\.be/)([^""&?/ ]{11})

# youtube-dl -x --postprocessor-args "-ss $3 -to $4" $1 -o
SAMPLES_PATH="/home/begin/stream/Stream/Samples/$2*"

echo $SAMPLES_PATH

# if [[ -z "$3" && -z "$4" ]]
# then
#   youtube-dl -x "$1" -o "$2.%(ext)s"
# else
#   echo "Cutting from $3 to $4"
#   youtube-dl -x --postprocessor-args "-ss $3 -to $4" $1 -o "/home/begin/stream/Stream/Samples/$2.%(ext)s"
# fi
